### PR TITLE
Many things

### PR DESCRIPTION
**Pull request by ScoreUnder**
* Changed how the file printing works (the loop is implicit, and it uses a format string now)
* Used `lstat` once on each file rather than `isfile` / `isdir` / `getsize` etc.
* Filtered dotfiles (when no `-a` given) right at the start of the script so there's no need to put that code into all the print routines and the sorting routine
* Made `byte_to` work up to exabytes and replaced the cascaded `if`/`elif` with a loop
* Changed `ls -f` back to using one decimal digit when displaying file sizes. To change this back you'd probably need to add some extra keyword arguments to the printing function (or introduce a class to keep some state for the formatting).
* Some smaller changes (see commit messages)

There might be some changes you disagree with in here so if you want me to split it up please ask.

Please read through the commit diffs, and if there's anything you don't understand you might want to hold off on merging (I don't want to offload all this code on you and leave it in a state where you can't maintain your own program).

Some recommended reading:

* [`strftime` docs](https://docs.python.org/2/library/time.html#time.strftime) -- This is where I got "%c" from in the format for the date. You can replace it with anything according to that table (for example `%b %Y`) to change the format it will display in the file listing.
* [`lstat` and `stat` docs](https://docs.python.org/2/library/os.html#os.lstat) --  Used to get a fair amount of info about a file all at once. Much more efficient than requesting each piece of info individually.
  * [`stat` module](https://docs.python.org/2/library/stat.html) -- for functions which make sense of the `st_mode` part of `stat`'s return value

Stuff I think still needs doing after this (I'll leave it to you, and you can decide if they're important to you):

* Restructure the file list so that it includes the files' `stat`s. That will let you sort without re-checking the file's size.
* Use `argparse`
* Take the last value of `-d`, `-f`, or `-c` instead of the first (this means if you do `alias a='a -f'`, then you can still run `a -c` without being stuck with the full listing)
* Cut down on global variable usage (maybe?)
* Follow pep8 standards
* Either throw an error if there's more than one directory asked for, or list all of them one after the other.

### CODE REVIEW

**Comment by hdev1** [comment]
Thanks for the fixes, really appreciate it.

**Comment by hdev1** [comment]
I don't like to add code without understanding it, I'll take my time to understand what you've changed and then merge :)

**Comment by hdev1** [comment]
Mind explaining the **print_keywords thing?

**Comment by ScoreUnder** [comment]
Sure.

There's a good explanation here: http://hangar.runway7.net/python/packing-unpacking-arguments

But in my own words:

```python
def func(arg1, *args, **kwargs):
```

The above function definition can be called like this: `func(123)`. Both `*args` and `**kwargs` are optional. You can call it with `func(123,456,789)`, and then `arg1` will have `123` as usual, but `args` will be a tuple containing the remaining `(456,789)`. You can call it as `func(123, cats='tabby', dogs=None)` and it will fill `arg1` as normal, give an empty tuple for `args`, and give a dictionary for `kwargs` containing `{'cats': 'tabby', 'dogs': None}`.

So practically speaking, `*args` and `**kwargs` will take any "leftover" arguments to the function which aren't specified in that function's definition. `*args` is for the un-named arguments, and `**kwargs` is for the named ones.

You can use the `*` and `**` operator the other way around too:

```python
args = ["Hello", "World"]
kwargs = {'end': '!\n'}
print(*args, **kwargs)
```
This is equivalent to `print("Hello", "World", end='!\n')`.

What I use this for in this pull request is to pass extra arguments to `print`. I use `**`, so it will take any extra keyword arguments (i.e. `name=value` kind of arguments) and put them into that variable. I don't really touch that variable much other than to pass it into `print`, so that means if you call `print_files` with `end='', file=sys.stderr` (for example), it will eventually call `print(..., end='', file=sys.stderr)`. I use it to avoid newlines in the `-c` output.

**Comment by ScoreUnder** [comment]
I've merged in your branch's changes to resolve conflicts, I've also tweaked a couple of error conditions. I saw you had added an error condition in some branch in your code, but I'm not sure of whether that will occur or how to test it, so I've left that out. Given the possible functions it could have failed on, I'd also recommend you run a fsck.

**Comment by hdev1** [comment]
Okay, well thanks for the work you've done. I've learned a few things for sure.

**Pull request merged**
